# Generated by Django 5.0.6 on 2024-07-08 05:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agendamentos', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='agendamento',
            name='agendamento_id',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
