# Generated by Django 5.0.6 on 2024-07-08 16:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('agendamentos', '0003_agendamento_agendamento_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='agendamento',
            name='agendamento_id',
        ),
    ]
