# Generated by Django 5.0.6 on 2024-07-13 13:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agendamentos', '0004_remove_agendamento_agendamento_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agendamento',
            name='status',
            field=models.CharField(choices=[('pendente', 'Pendente'), ('agendado', 'Agendado'), ('finalizado', 'Finalizado'), ('cancelado', 'Cancelado')], default='pendente', max_length=20),
        ),
    ]
