# Generated by Django 5.0.6 on 2024-07-08 02:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('agendamentos', '0002_initial'),
        ('estoque', '0001_initial'),
        ('usuarios', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Venda',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('desconto', models.FloatField(blank=True, null=True)),
                ('valor_total', models.FloatField()),
                ('data_hora_venda', models.DateTimeField(auto_now_add=True)),
                ('status_pagamento', models.CharField(choices=[('Em Aberto', 'Em Aberto'), ('Pago', 'Pago'), ('Cancelado', 'Cancelado')], default='Em Aberto', max_length=20)),
                ('comprovante_pix', models.CharField(blank=True, max_length=200, null=True)),
                ('valor_comissao', models.FloatField()),
                ('agendamento', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='agendamentos.agendamento')),
                ('barbeiro', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='usuarios.barbeiro')),
            ],
        ),
        migrations.CreateModel(
            name='VendaProduto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantidade', models.IntegerField()),
                ('produto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='estoque.produto')),
                ('venda', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vendas.venda')),
            ],
        ),
        migrations.AddField(
            model_name='venda',
            name='produtos',
            field=models.ManyToManyField(through='vendas.VendaProduto', to='estoque.produto'),
        ),
    ]
