# Generated by Django 5.0.6 on 2024-07-12 17:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vendas', '0003_alter_venda_desconto_alter_venda_valor_comissao_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='vendaproduto',
            name='preco_unitario',
            field=models.DecimalField(decimal_places=2, default=1, max_digits=10),
            preserve_default=False,
        ),
    ]
