# Generated by Django 5.0.6 on 2024-07-13 02:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vendas', '0004_vendaproduto_preco_unitario'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vendaproduto',
            name='preco_unitario',
        ),
    ]
