# Generated by Django 5.0.6 on 2024-07-13 05:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vendas', '0007_alter_vendaproduto_preco_unitario'),
    ]

    operations = [
        migrations.AlterField(
            model_name='venda',
            name='status_pagamento',
            field=models.CharField(choices=[('Em Aberto', 'Em Aberto'), ('Fechada', 'Fechada'), ('Reaberta', 'Reaberta'), ('Pago', 'Pago'), ('Cancelado', 'Cancelado')], default='Em Aberto', max_length=20),
        ),
    ]
