# Generated by Django 5.0.6 on 2024-07-13 22:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vendas', '0008_alter_venda_status_pagamento'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='venda',
            name='desconto',
        ),
    ]
