# Generated by Django 5.0.6 on 2024-07-08 05:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Caixa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valor_abertura', models.FloatField(default=0)),
                ('valor_fechamento', models.FloatField(blank=True, null=True)),
            ],
        ),
    ]
