# Generated by Django 5.0.6 on 2024-07-13 05:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('caixa', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='caixa',
            name='valor_abertura',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=5),
        ),
        migrations.AlterField(
            model_name='caixa',
            name='valor_fechamento',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=5),
        ),
    ]
