# Generated by Django 5.0.6 on 2024-07-13 05:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('caixa', '0002_alter_caixa_valor_abertura_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='caixa',
            name='valor_abertura',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='caixa',
            name='valor_fechamento',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
    ]
